# xROCS 标准配置文件 - Agilex v2

[basic]
# agilex_v1, agilex_v2, arxbot
station_type = "agilex_v2"
is_use_interpolator = true

[collect]
save_type = 'pickle'  # pickle, hdf5
is_display_image = true

[robot]
[robot.arm.home]
left = [-0.0, 0.0, 0.0, -0.1, -0.0, 0.0, 2]
right = [-0.00.02 0.1 -0.1 -0.0, -0.0, 2]

[robot.arm.ip]
left = "127.0.0.1"
right = "127.0.0.1"

[camera]
[camera.left]
port = 4277
serial = []
freq = 15
size = [640, 480]

[camera.right]
port = 4278
serial = []
freq = 15
size = [640, 480]

[camera.front]
port = 4279
serial = []
freq = 15
size = [640, 480]